// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom Coded UI-Test-Generator generiert.
//      Version: 14.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      Coded UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject7
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// FML - Verwenden Sie "FMLParams", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void FML()
        {
            #region Variable Declarations
            WinEdit uINameEdit = this.UIDebugWindow.UIItemWindow.UIM120LB2FS17ListItem.UINameEdit;
            WpfListItem uISystemDynamicExpandoListItem = this.UIMainWindowWindow.UILb_vermietungList.UISystemDynamicExpandoListItem;
            WpfButton uINeuButton = this.UIMainWindowWindow.UIItemCustom.UINeuButton;
            WpfButton uIItemButton = this.UIMainWindowWindow.UIItemCustom.UIDg_vermietungTable.UIItem0Row.UIElement0AnzeigeindexCell.UIItemButton;
            WpfText uIBorisText = this.UIMainWindowWindow.UIUc_selectKundenCustom.UIDg_listeTable.UIItem2Row.UIBorisCell.UIBorisText;
            WpfButton uISpeichernButton = this.UIMainWindowWindow.UIUc_selectKundenCustom.UISpeichernButton;
            WpfButton uIItemButton1 = this.UIMainWindowWindow.UIItemCustom.UIDg_vermietungTable.UIItem0Row.UIElement0AnzeigeindexCell1.UIItemButton;
            WpfText uITourdeSuisseText = this.UIMainWindowWindow.UIUc_selectFahrradCustom.UIDg_listeTable.UIItem2Row.UITourdeSuisseCell.UITourdeSuisseText;
            WpfButton uISpeichernButton1 = this.UIMainWindowWindow.UIUc_selectFahrradCustom.UISpeichernButton;
            WpfText uIItem110001120000AMText = this.UIMainWindowWindow.UIItemCustom.UIDg_vermietungTable.UIItem0Row.UIItem110001120000AMCell.UIItem110001120000AMText;
            WinList uIElementansichtList = this.UIDebugWindow.UIShellViewWindow.UIShellViewClient.UIElementansichtList;
            WpfEdit uIItemEdit = this.UIMainWindowWindow.UIItemCustom.UIDg_vermietungTable.UIItem0Row.UIItem110001120000AMCell.UIItemEdit;
            WpfText uIItem110001120000AMText1 = this.UIMainWindowWindow.UIItemCustom.UIDg_vermietungTable.UIItem0Row.UIItem110001120000AMCell1.UIItem110001120000AMText;
            WinButton uISchließenButton = this.UIMainWindowWindow1.UISchließenButton;
            #endregion

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit, new Point(80, 10));

            // Klicken "System.Dynamic.ExpandoObject" Listenelement
            Mouse.Click(uISystemDynamicExpandoListItem, new Point(105, 13));

            // Klicken "Neu" Schaltfläche
            Mouse.Click(uINeuButton, new Point(193, 9));

            // Klicken Schaltfläche
            Mouse.Click(uIItemButton, new Point(18, 13));

            // Klicken "Boris" Bezeichnung
            Mouse.Click(uIBorisText, new Point(2, 10));

            // Klicken "Speichern" Schaltfläche
            Mouse.Click(uISpeichernButton, new Point(124, 12));

            // Klicken Schaltfläche
            Mouse.Click(uIItemButton1, new Point(31, 14));

            // Klicken "Tour de Suisse" Bezeichnung
            Mouse.Click(uITourdeSuisseText, new Point(59, 8));

            // Klicken "Tour de Suisse" Bezeichnung
            Mouse.Click(uITourdeSuisseText, new Point(59, 8));

            // Klicken "Speichern" Schaltfläche
            Mouse.Click(uISpeichernButton1, new Point(257, 21));

            // Klicken "1/1/0001 12:00:00 AM" Bezeichnung
            Mouse.Click(uIItem110001120000AMText, new Point(79, 6));

            // "{NumPad1}{NumPad4}{LShiftKey}{Divide}{NumPad6}{LShiftKey}{Divide}{NumPad1}{NumPad7}{Space}{NumPad0}{NumPad9}{LShiftKey}:00{Tab}" in "Elementansicht" Listenfeld eingeben
            Keyboard.SendKeys(uIElementansichtList, this.FMLParams.UIElementansichtListSendKeys, ModifierKeys.None);

            // Textfeld  verschieben
            //Der Systemparameter "Fensterinhalt beim Ziehen anzeigen" ist nicht festgelegt. Dies kann dazu führen, dass Ziehaktionen falsch aufgezeichnet werden.
            Mouse.StartDragging(uIItemEdit, new Point(90, 14), MouseButtons.Left, ModifierKeys.None);
            Mouse.StopDragging(uIItemEdit, -84, -4);

            // "{Right}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{NumPad2}{NumPad0}{Tab}{NumPad1}{NumPad4}{Divide}" in "Elementansicht" Listenfeld eingeben
            Keyboard.SendKeys(uIElementansichtList, this.FMLParams.UIElementansichtListSendKeys1, ModifierKeys.None);

            // Klicken "1/1/0001 12:00:00 AM" Bezeichnung
            Mouse.Click(uIItem110001120000AMText1, new Point(74, 1));

            // Doppelklicken "1/1/0001 12:00:00 AM" Bezeichnung
            Mouse.DoubleClick(uIItem110001120000AMText1, new Point(69, 8));

            // Doppelklicken Textfeld
            Mouse.DoubleClick(uIItemEdit, new Point(90, 11));

            // "{Right}{LShiftKey}:{Space}00{Back}{Back}{Back}00{Space}{CapsLock}AMA{Back}{Tab}{NumPad1}" in "Elementansicht" Listenfeld eingeben
            Keyboard.SendKeys(uIElementansichtList, this.FMLParams.UIElementansichtListSendKeys2, ModifierKeys.None);

            // "{NumPad4}{NumPad1}{NumPad4}" in "Elementansicht" Listenfeld eingeben
            Keyboard.SendKeys(uIElementansichtList, this.FMLParams.UIElementansichtListSendKeys3, ModifierKeys.None);

            // Klicken "Schließen" Schaltfläche
            Mouse.Click(uISchließenButton, new Point(16, 7));
        }
        
        #region Properties
        public virtual FMLParams FMLParams
        {
            get
            {
                if ((this.mFMLParams == null))
                {
                    this.mFMLParams = new FMLParams();
                }
                return this.mFMLParams;
            }
        }
        
        public UIDebugWindow UIDebugWindow
        {
            get
            {
                if ((this.mUIDebugWindow == null))
                {
                    this.mUIDebugWindow = new UIDebugWindow();
                }
                return this.mUIDebugWindow;
            }
        }
        
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        
        public UIMainWindowWindow1 UIMainWindowWindow1
        {
            get
            {
                if ((this.mUIMainWindowWindow1 == null))
                {
                    this.mUIMainWindowWindow1 = new UIMainWindowWindow1();
                }
                return this.mUIMainWindowWindow1;
            }
        }
        #endregion
        
        #region Fields
        private FMLParams mFMLParams;
        
        private UIDebugWindow mUIDebugWindow;
        
        private UIMainWindowWindow mUIMainWindowWindow;
        
        private UIMainWindowWindow1 mUIMainWindowWindow1;
        #endregion
    }
    
    /// <summary>
    /// An "FML" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class FMLParams
    {
        
        #region Fields
        /// <summary>
        /// "{NumPad1}{NumPad4}{LShiftKey}{Divide}{NumPad6}{LShiftKey}{Divide}{NumPad1}{NumPad7}{Space}{NumPad0}{NumPad9}{LShiftKey}:00{Tab}" in "Elementansicht" Listenfeld eingeben
        /// </summary>
        public string UIElementansichtListSendKeys = "{NumPad1}{NumPad4}{LShiftKey}{Divide}{NumPad6}{LShiftKey}{Divide}{NumPad1}{NumPad" +
            "7}{Space}{NumPad0}{NumPad9}{LShiftKey}:00{Tab}";
        
        /// <summary>
        /// "{Right}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{NumPad2}{NumPad0}{Tab}{NumPad1}{NumPad4}{Divide}" in "Elementansicht" Listenfeld eingeben
        /// </summary>
        public string UIElementansichtListSendKeys1 = "{Right}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{Left}{NumPad2}{NumPad0}{Tab}{Nu" +
            "mPad1}{NumPad4}{Divide}";
        
        /// <summary>
        /// "{Right}{LShiftKey}:{Space}00{Back}{Back}{Back}00{Space}{CapsLock}AMA{Back}{Tab}{NumPad1}" in "Elementansicht" Listenfeld eingeben
        /// </summary>
        public string UIElementansichtListSendKeys2 = "{Right}{LShiftKey}:{Space}00{Back}{Back}{Back}00{Space}{CapsLock}AMA{Back}{Tab}{N" +
            "umPad1}";
        
        /// <summary>
        /// "{NumPad4}{NumPad1}{NumPad4}" in "Elementansicht" Listenfeld eingeben
        /// </summary>
        public string UIElementansichtListSendKeys3 = "{NumPad4}{NumPad1}{NumPad4}";
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIDebugWindow : WinWindow
    {
        
        public UIDebugWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Debug";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIShellViewWindow UIShellViewWindow
        {
            get
            {
                if ((this.mUIShellViewWindow == null))
                {
                    this.mUIShellViewWindow = new UIShellViewWindow(this);
                }
                return this.mUIShellViewWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIShellViewWindow mUIShellViewWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Elementansicht";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UIM120LB2FS17ListItem UIM120LB2FS17ListItem
        {
            get
            {
                if ((this.mUIM120LB2FS17ListItem == null))
                {
                    this.mUIM120LB2FS17ListItem = new UIM120LB2FS17ListItem(this);
                }
                return this.mUIM120LB2FS17ListItem;
            }
        }
        #endregion
        
        #region Fields
        private UIM120LB2FS17ListItem mUIM120LB2FS17ListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIM120LB2FS17ListItem : WinListItem
    {
        
        public UIM120LB2FS17ListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinListItem.PropertyNames.Name] = "M120-LB2-FS17";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIShellViewWindow : WinWindow
    {
        
        public UIShellViewWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ShellView";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "SHELLDLL_DefView";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UIShellViewClient UIShellViewClient
        {
            get
            {
                if ((this.mUIShellViewClient == null))
                {
                    this.mUIShellViewClient = new UIShellViewClient(this);
                }
                return this.mUIShellViewClient;
            }
        }
        #endregion
        
        #region Fields
        private UIShellViewClient mUIShellViewClient;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIShellViewClient : WinClient
    {
        
        public UIShellViewClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinControl.PropertyNames.Name] = "Shellordneransicht";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinList UIElementansichtList
        {
            get
            {
                if ((this.mUIElementansichtList == null))
                {
                    this.mUIElementansichtList = new WinList(this);
                    #region Suchkriterien
                    this.mUIElementansichtList.SearchProperties[WinList.PropertyNames.Name] = "Elementansicht";
                    this.mUIElementansichtList.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUIElementansichtList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUIElementansichtList;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UILb_vermietungList UILb_vermietungList
        {
            get
            {
                if ((this.mUILb_vermietungList == null))
                {
                    this.mUILb_vermietungList = new UILb_vermietungList(this);
                }
                return this.mUILb_vermietungList;
            }
        }
        
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        
        public UIUc_selectKundenCustom UIUc_selectKundenCustom
        {
            get
            {
                if ((this.mUIUc_selectKundenCustom == null))
                {
                    this.mUIUc_selectKundenCustom = new UIUc_selectKundenCustom(this);
                }
                return this.mUIUc_selectKundenCustom;
            }
        }
        
        public UIUc_selectFahrradCustom UIUc_selectFahrradCustom
        {
            get
            {
                if ((this.mUIUc_selectFahrradCustom == null))
                {
                    this.mUIUc_selectFahrradCustom = new UIUc_selectFahrradCustom(this);
                }
                return this.mUIUc_selectFahrradCustom;
            }
        }
        #endregion
        
        #region Fields
        private UILb_vermietungList mUILb_vermietungList;
        
        private UIItemCustom mUIItemCustom;
        
        private UIUc_selectKundenCustom mUIUc_selectKundenCustom;
        
        private UIUc_selectFahrradCustom mUIUc_selectFahrradCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UILb_vermietungList : WpfList
    {
        
        public UILb_vermietungList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfList.PropertyNames.AutomationId] = "lb_vermietung";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfListItem UISystemDynamicExpandoListItem
        {
            get
            {
                if ((this.mUISystemDynamicExpandoListItem == null))
                {
                    this.mUISystemDynamicExpandoListItem = new WpfListItem(this);
                    #region Suchkriterien
                    this.mUISystemDynamicExpandoListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "System.Dynamic.ExpandoObject";
                    this.mUISystemDynamicExpandoListItem.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISystemDynamicExpandoListItem;
            }
        }
        #endregion
        
        #region Fields
        private WpfListItem mUISystemDynamicExpandoListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.VermietungEinzelansicht";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfButton UINeuButton
        {
            get
            {
                if ((this.mUINeuButton == null))
                {
                    this.mUINeuButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUINeuButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btn_neu";
                    this.mUINeuButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUINeuButton;
            }
        }
        
        public UIDg_vermietungTable UIDg_vermietungTable
        {
            get
            {
                if ((this.mUIDg_vermietungTable == null))
                {
                    this.mUIDg_vermietungTable = new UIDg_vermietungTable(this);
                }
                return this.mUIDg_vermietungTable;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUINeuButton;
        
        private UIDg_vermietungTable mUIDg_vermietungTable;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIDg_vermietungTable : WpfTable
    {
        
        public UIDg_vermietungTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "dg_vermietung";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItem0Row UIItem0Row
        {
            get
            {
                if ((this.mUIItem0Row == null))
                {
                    this.mUIItem0Row = new UIItem0Row(this);
                }
                return this.mUIItem0Row;
            }
        }
        #endregion
        
        #region Fields
        private UIItem0Row mUIItem0Row;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIItem0Row : WpfRow
    {
        
        public UIItem0Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfRow.PropertyNames.Name] = "0";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIElement0AnzeigeindexCell UIElement0AnzeigeindexCell
        {
            get
            {
                if ((this.mUIElement0AnzeigeindexCell == null))
                {
                    this.mUIElement0AnzeigeindexCell = new UIElement0AnzeigeindexCell(this);
                }
                return this.mUIElement0AnzeigeindexCell;
            }
        }
        
        public UIElement0AnzeigeindexCell1 UIElement0AnzeigeindexCell1
        {
            get
            {
                if ((this.mUIElement0AnzeigeindexCell1 == null))
                {
                    this.mUIElement0AnzeigeindexCell1 = new UIElement0AnzeigeindexCell1(this);
                }
                return this.mUIElement0AnzeigeindexCell1;
            }
        }
        
        public UIItem110001120000AMCell UIItem110001120000AMCell
        {
            get
            {
                if ((this.mUIItem110001120000AMCell == null))
                {
                    this.mUIItem110001120000AMCell = new UIItem110001120000AMCell(this);
                }
                return this.mUIItem110001120000AMCell;
            }
        }
        
        public UIItem110001120000AMCell1 UIItem110001120000AMCell1
        {
            get
            {
                if ((this.mUIItem110001120000AMCell1 == null))
                {
                    this.mUIItem110001120000AMCell1 = new UIItem110001120000AMCell1(this);
                }
                return this.mUIItem110001120000AMCell1;
            }
        }
        #endregion
        
        #region Fields
        private UIElement0AnzeigeindexCell mUIElement0AnzeigeindexCell;
        
        private UIElement0AnzeigeindexCell1 mUIElement0AnzeigeindexCell1;
        
        private UIItem110001120000AMCell mUIItem110001120000AMCell;
        
        private UIItem110001120000AMCell1 mUIItem110001120000AMCell1;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIElement0AnzeigeindexCell : WpfCell
    {
        
        public UIElement0AnzeigeindexCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Kunde";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUIItemButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIItemButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIElement0AnzeigeindexCell1 : WpfCell
    {
        
        public UIElement0AnzeigeindexCell1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Fahrrad";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUIItemButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIItemButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIItem110001120000AMCell : WpfCell
    {
        
        public UIItem110001120000AMCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Start";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UIItem110001120000AMText
        {
            get
            {
                if ((this.mUIItem110001120000AMText == null))
                {
                    this.mUIItem110001120000AMText = new WpfText(this);
                    #region Suchkriterien
                    this.mUIItem110001120000AMText.SearchProperties[WpfText.PropertyNames.Name] = "1/1/0001 12:00:00 AM";
                    this.mUIItem110001120000AMText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIItem110001120000AMText;
            }
        }
        
        public WpfEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WpfEdit(this);
                    #region Suchkriterien
                    this.mUIItemEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIItem110001120000AMText;
        
        private WpfEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIItem110001120000AMCell1 : WpfCell
    {
        
        public UIItem110001120000AMCell1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Ende";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UIItem110001120000AMText
        {
            get
            {
                if ((this.mUIItem110001120000AMText == null))
                {
                    this.mUIItem110001120000AMText = new WpfText(this);
                    #region Suchkriterien
                    this.mUIItem110001120000AMText.SearchProperties[WpfText.PropertyNames.Name] = "1/1/0001 12:00:00 AM";
                    this.mUIItem110001120000AMText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIItem110001120000AMText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIItem110001120000AMText;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIUc_selectKundenCustom : WpfCustom
    {
        
        public UIUc_selectKundenCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.selectKunden";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "uc_selectKunden";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIDg_listeTable UIDg_listeTable
        {
            get
            {
                if ((this.mUIDg_listeTable == null))
                {
                    this.mUIDg_listeTable = new UIDg_listeTable(this);
                }
                return this.mUIDg_listeTable;
            }
        }
        
        public WpfButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUISpeichernButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btn_save";
                    this.mUISpeichernButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        #endregion
        
        #region Fields
        private UIDg_listeTable mUIDg_listeTable;
        
        private WpfButton mUISpeichernButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIDg_listeTable : WpfTable
    {
        
        public UIDg_listeTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "dg_liste";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItem2Row UIItem2Row
        {
            get
            {
                if ((this.mUIItem2Row == null))
                {
                    this.mUIItem2Row = new UIItem2Row(this);
                }
                return this.mUIItem2Row;
            }
        }
        #endregion
        
        #region Fields
        private UIItem2Row mUIItem2Row;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIItem2Row : WpfRow
    {
        
        public UIItem2Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfRow.PropertyNames.Name] = "2";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIBorisCell UIBorisCell
        {
            get
            {
                if ((this.mUIBorisCell == null))
                {
                    this.mUIBorisCell = new UIBorisCell(this);
                }
                return this.mUIBorisCell;
            }
        }
        #endregion
        
        #region Fields
        private UIBorisCell mUIBorisCell;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIBorisCell : WpfCell
    {
        
        public UIBorisCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Vorname";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UIBorisText
        {
            get
            {
                if ((this.mUIBorisText == null))
                {
                    this.mUIBorisText = new WpfText(this);
                    #region Suchkriterien
                    this.mUIBorisText.SearchProperties[WpfText.PropertyNames.Name] = "Boris";
                    this.mUIBorisText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIBorisText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIBorisText;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIUc_selectFahrradCustom : WpfCustom
    {
        
        public UIUc_selectFahrradCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.selectFahrrad";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "uc_selectFahrrad";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIDg_listeTable1 UIDg_listeTable
        {
            get
            {
                if ((this.mUIDg_listeTable == null))
                {
                    this.mUIDg_listeTable = new UIDg_listeTable1(this);
                }
                return this.mUIDg_listeTable;
            }
        }
        
        public WpfButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUISpeichernButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btn_save";
                    this.mUISpeichernButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        #endregion
        
        #region Fields
        private UIDg_listeTable1 mUIDg_listeTable;
        
        private WpfButton mUISpeichernButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIDg_listeTable1 : WpfTable
    {
        
        public UIDg_listeTable1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "dg_liste";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItem2Row1 UIItem2Row
        {
            get
            {
                if ((this.mUIItem2Row == null))
                {
                    this.mUIItem2Row = new UIItem2Row1(this);
                }
                return this.mUIItem2Row;
            }
        }
        #endregion
        
        #region Fields
        private UIItem2Row1 mUIItem2Row;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIItem2Row1 : WpfRow
    {
        
        public UIItem2Row1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfRow.PropertyNames.Name] = "2";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UITourdeSuisseCell UITourdeSuisseCell
        {
            get
            {
                if ((this.mUITourdeSuisseCell == null))
                {
                    this.mUITourdeSuisseCell = new UITourdeSuisseCell(this);
                }
                return this.mUITourdeSuisseCell;
            }
        }
        #endregion
        
        #region Fields
        private UITourdeSuisseCell mUITourdeSuisseCell;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UITourdeSuisseCell : WpfCell
    {
        
        public UITourdeSuisseCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Hersteller";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UITourdeSuisseText
        {
            get
            {
                if ((this.mUITourdeSuisseText == null))
                {
                    this.mUITourdeSuisseText = new WpfText(this);
                    #region Suchkriterien
                    this.mUITourdeSuisseText.SearchProperties[WpfText.PropertyNames.Name] = "Tour de Suisse";
                    this.mUITourdeSuisseText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITourdeSuisseText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUITourdeSuisseText;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIMainWindowWindow1 : WinWindow
    {
        
        public UIMainWindowWindow1()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WinButton UISchließenButton
        {
            get
            {
                if ((this.mUISchließenButton == null))
                {
                    this.mUISchließenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUISchließenButton.SearchProperties[WinButton.PropertyNames.Name] = "Schließen";
                    this.mUISchließenButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISchließenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISchließenButton;
        #endregion
    }
}
